### ISSUE TITLE
Tool not providing output 

### ISSUE THREAD

**Issue by securitybites** [Ice3man543/SubOver#4]
When running the tool against a list there isn't any output from the tool within the terminal or the output file. It seems like the tool isn't actually running against the targets and just exits.

OS: High Sierra

**Comment by securitybites** [comment]
Looks like the issue is that the hosts.txt file that is accepted by -l requires Windows style line separators.

**Comment by Ice3man543** [comment]
As noted in the python docs, it uses windows style for defaults. Actually, I don't have a mac therefore I didn't test it on a mac. I will fix it soon. 

As a side note, have you used the verbose switch with tool?

**Comment by Ice3man543** [comment]
The universal newline switch is deprecated in python2.7. I think explicitly setting the newline flag to None in open call would solve the problem.

**Comment by Ice3man543** [comment]
Hi there. I think the issue may exist only on your PC. To verify this, please open a terminal and type python to open interactive console. Also make sure you are using python2. To verify, please type the following code 

domainfile = open(domainlist)
for target in domainfile:
      print targets

Basically this will get you the lines of text. If this works, then we can assume code has some problem. Else the problem lies with your system or formatting of the targets file.
