### ISSUE TITLE
providers.json

### ISSUE THREAD

**Issue by its0x08** [Ice3man543/SubOver#8]
hello,
congrats for the tool, is awesome..!
can you please consider in the next release embedding providers.json in the tool so i wont have to change directory everytime i wanna scan some text file that is in an other dir ..
thanks

**Comment by Ice3man543** [comment]
Hey @its0x08, I considered embedding provider.json in the tool itself but did not do it because I wanted it to be simple to add new services and fingerprints whenever required. As a result, you don't need to recompile the whole thing to fix one simple problem. I may consider adding it in next release, but for now on it will remain like this.

**Comment by its0x08** [comment]
Maybe I will have to throw providers in /usr/bin and then it'll work.
Thank you for your time.

**Comment by Ice3man543** [comment]
No problem. Have fun. :smile:
